In [1]:
import pandas as pd

In [19]:
csv_file = pd.DataFrame(pd.read_csv("CN_Employment_Data.csv", sep = ",", header = 0))
df1_transposed = csv_file.T
df1_transposed.columns = ['Employed population', 'Employed Population in City', 'Unemployment rate']

In [9]:
csv_file.to_json("CN_Employment.json", orient = "records", date_format = "epoch", double_precision = 10, force_ascii = True, date_unit = "ms", default_handler = None)

In [28]:
CN_employment_data = df1_transposed.drop("Unnamed: 0")

In [31]:
csv_file2 = pd.DataFrame(pd.read_csv("CN_Province_Unemployment_Rate.csv", sep = ",", header = 0))
df2_transposed = csv_file2.T
city_name = csv_file2.iloc[:, 0].tolist()
df2_transposed.columns = city_name
CN_unemployment_data = df2_transposed.drop("Unnamed: 0")

In [49]:
CN_employment_data

     Employed population Employed Population in City Unemployment rate
2021               74652                       46773                 4
2020               75064                       46271               4.2
2019               75447                       45249               3.6
2018               75782                       44292               3.8
2017               76058                       43208               3.9
2016               76245                       42051                 4
2015               76320                       40916               4.1
2014               76349                       39703               4.1
2013               76301                       38527               4.1
2012               76254                       37287               4.1

In [50]:
CN_unemployment_data

,Beijing,Tianjing,Hebei,Shanxi,Neimenggu,Liaoning,Jilin,Heilongjiang,Shanghai,Jiangsu,...,Chongqing,Sichuan,Guizhou,Yunnan,Xizang,Shaanxi,Gansu,Qinghai,Ningxia,Xinjiang
2020,2.6,3.6,3.5,3.1,3.8,4.6,3.4,3.4,3.7,3.2,...,4.5,3.6,3.8,3.9,2.9,3.6,3.3,2.1,3.9,2.4
2019,1.3,3.5,3.1,2.7,3.7,4.2,3.1,3.5,3.6,3,...,2.6,3.3,3.1,3.3,2.9,3.2,3,2.2,3.7,2.1
2018,1.4,3.5,3.3,3.3,3.6,3.9,3.5,4,3.5,3,...,3,3.5,3.2,3.4,2.8,3.2,2.8,3,3.9,2.4
2017,1.4,3.5,3.7,3.4,3.6,3.8,3.5,4.2,3.9,3,...,3.4,4,3.2,3.2,2.7,3.3,2.7,3.1,3.9,2.6
2016,1.4,3.5,3.7,3.5,3.7,3.8,3.5,4.2,4.1,3,...,3.7,4.2,3.2,3.6,2.6,3.3,2.2,3.1,3.9,2.5
2015,1.4,3.5,3.6,3.5,3.7,3.4,3.5,4.5,4,3,...,3.6,4.1,3.3,4,2.5,3.4,2.1,3.2,4,2.9
2014,1.3,3.5,3.6,3.4,3.6,3.4,3.4,4.5,4.1,3,...,3.5,4.2,3.3,4,2.5,3.3,2.2,3.2,4,3.2
2013,1.2,3.6,3.7,3.1,3.7,3.4,3.7,4.4,4,3,...,3.4,4.1,3.3,4,2.5,3.3,2.3,3.3,4.1,3.4
2012,1.3,3.6,3.7,3.3,3.7,3.6,3.7,4.2,3.1,3.1,...,3.3,4,3.3,4,2.6,3.2,2.7,3.4,4.2,3.4

In [52]:
CN_employment_data.to_csv('clean_CN_employment_data.csv')
CN_unemployment_data.to_csv('clean_CN_Province_unemployment_data.csv')

In [59]:
CN_employment_data.to_json('CN_employment_data.json',orient='index')
CN_unemployment_data.to_json('CN_Province_unemployment_data.json',orient='index')